import type { CardVM, WebviewToHost } from "@maestro/cockpit";
import { renderReview } from "../review-render.js";
import { parseUnifiedDiff } from "../diff-parse.js";
import type { ReviewOpenOpts, HostToReview } from "../review.js";

interface VsCodeApi {
  postMessage(msg: WebviewToHost): void;
}
declare function acquireVsCodeApi(): VsCodeApi;

const vscode = acquireVsCodeApi();
const root = document.getElementById("root");

// Track the currently-displayed card so sendBack can read the textarea value.
let currentCard: CardVM | undefined;
let currentOpts: ReviewOpenOpts = {};

function render(card: CardVM, opts: ReviewOpenOpts): void {
  if (!root) return;
  currentCard = card;
  currentOpts = opts;
  const parsed = parseUnifiedDiff(card.diff?.patch ?? "");
  root.innerHTML = renderReview(card, parsed, opts);
}

// ─── Host message listener ────────────────────────────────────────────────────

window.addEventListener("message", (e: MessageEvent<HostToReview>) => {
  const data = e.data;
  if (data.type === "review-state") {
    render(data.card, data.opts);
  }
});

// ─── Steer + send-back forms ──────────────────────────────────────────────────

document.addEventListener("submit", (e) => {
  const form = e.target;
  if (!(form instanceof HTMLFormElement)) return;
  const action = form.dataset["action"];
  const id = form.dataset["id"];
  if (!id) return;
  if (action === "steer") {
    e.preventDefault();
    const input = form.querySelector<HTMLInputElement>(".steer-input");
    const text = input?.value.trim();
    if (!text) return;
    vscode.postMessage({ type: "steer", agentId: id, input: text });
    if (input) input.value = "";
  } else if (action === "sendBack") {
    e.preventDefault();
    const textarea = form.querySelector<HTMLTextAreaElement>(".sendback-input");
    const text = textarea?.value.trim();
    if (!text) return;
    vscode.postMessage({ type: "sendBack", agentId: id, feedback: text });
    if (textarea) textarea.value = "";
  }
});

// ─── Click delegation ─────────────────────────────────────────────────────────

document.addEventListener("click", (e) => {
  const target = e.target;
  if (!(target instanceof HTMLElement)) return;

  const btn = target.closest<HTMLElement>("[data-action]");
  if (!btn) return;

  const id = btn.dataset["id"];
  const action = btn.dataset["action"];

  // open-review is a board-only affordance; review-main does not re-open itself.
  // sendBack in the decision-bar needs the textarea value, which decisionBar
  // renders inline in review-render; the form submit handler above covers it.
  // For direct-button sendBack (no textarea), grab the closest textarea sibling.

  if (!id) return;

  if (action === "merge") {
    vscode.postMessage({ type: "merge", agentId: id });
  } else if (action === "discard") {
    vscode.postMessage({ type: "discard", agentId: id });
  } else if (action === "stop") {
    vscode.postMessage({ type: "stop", agentId: id });
  } else if (action === "approve") {
    const approvalId = btn.dataset["approvalId"];
    if (approvalId) {
      // M6 tool-approval (only present on awaiting-approval cards).
      vscode.postMessage({ type: "approve", agentId: id, approvalId, decision: "allow" });
    } else {
      // Review sign-off on a done/conflict card: "the work is good, but do not
      // merge yet." There is no backing orchestrator action for a soft sign-off,
      // so acknowledge it locally rather than silently dropping the click; the
      // card stays done on the board, ready to merge later.
      btn.textContent = "Approved";
      btn.setAttribute("disabled", "");
      (btn as HTMLButtonElement).style.opacity = "0.6";
    }
  } else if (action === "deny") {
    const approvalId = btn.dataset["approvalId"];
    if (approvalId) {
      vscode.postMessage({ type: "approve", agentId: id, approvalId, decision: "deny" });
    }
  } else if (action === "resolve-conflict") {
    vscode.postMessage({ type: "resolve-conflict", agentId: id });
  } else if (action === "finish-merge") {
    vscode.postMessage({ type: "finish-merge", agentId: id });
  } else if (action === "create-pr") {
    vscode.postMessage({ type: "create-pr", agentId: id });
  } else if (action === "retry-cleanup") {
    vscode.postMessage({ type: "retry-cleanup", agentId: id });
  } else if (action === "sendBack") {
    // Decision-bar sendBack button: read the adjacent textarea (generated by
    // review-render's decisionBar which places a textarea before the button).
    const footer = btn.closest("footer");
    const textarea = footer?.querySelector<HTMLTextAreaElement>("textarea");
    const text = textarea?.value.trim();
    if (text) {
      vscode.postMessage({ type: "sendBack", agentId: id, feedback: text });
      if (textarea) textarea.value = "";
    }
  }
});

vscode.postMessage({ type: "ready" });
